### PR TITLE
Some minor Krypton updates

### PR DESCRIPTION
**Pull request by MikeSiLVO**
Rename DialogYesNo to DialogConfirm so users can switch to skin
Rename settings window names and remove deprecated (Settings.xml still needs some removed)

### CODE REVIEW

**Comment by xhaggi** [comment]
Nice ... I'll do the necessary tests and merge it if fine.

Next time please mention me (@xhaggi) because I didn't got a notification as I'm not the owner of the repo. Thanks.

**Comment by xhaggi** [comment]
You only renamed `DialogYesNo.xml` to `DialogConfirm.xml` but leave the other dialogs untouched.

`DialogConfirm.xml`
- replaces `DialogOK.xml`
- replaces `DialogProgress.xml`
- replaces `DialogYesNo.xml`

see http://forum.kodi.tv/showthread.php?tid=250862&pid=2223875#pid2223875

We need to do it right before we can merge PR's. This is only a quick and dirty solution 😄

**Comment by xhaggi** [comment]
I've done the `DialogConfirm` merge in a1b938e7e20bbe064653ce3a18d72f187b251c40

**Comment by xhaggi** [comment]
I've done the setting window refactor in 00af62e4011eb8532963b8a5d6b9b5a02d0fdb8c

**Comment by MikeSiLVO** [comment]
@xhaggi This PR was to test the waters to see what the outcome would be. I didn't want to waste any time working on something that might sit for weeks or months and then be denied. I had asked you to clarify how you wanted to proceed in the Xperience thread thinking you had an issue with this PR (I thought you were denying it cause you wanted "logical" commits) but hearing now that you didn't get the notification makes me think we were talking about 2 separate things. 

I mentioned that I needed to change these things first so I could switch to the skin and be able to change options and so forth while working on other stuff at the same time. I thought a small but very functional PR was a good way to get what I needed in the skin so I could work on it while also getting some feedback from you at the same time.

To me this feels like the second time I assisted where it didn't feel appreciated. The first being that it is "good to hear I found a solution to the crashes" but not good enough for a Thanks. Don't actually need a thanks but it would have been nice to get some kind of acknowledgement that the time I spent to install a skin I don't use, to test and fix an issue I don't have, and to help out in a thread I don't visit was appreciated or at the very least didn't make me feel like crap for doing it.

I hope you do not think negatively of me but that's just how I feel...

**Comment by xhaggi** [comment]
don't get me wrong and sorry for not saying thank you after you share your fix in the forum. I took a look at this PR and thought nice someone is working on the Krypton stuff but after a quick look at the code I noticed that there are serveral things missing to merge it in. And that was the reason to start the work on Krypton by myself. Every contribution is much appreciated but it must be a done the right way before I can merge it in. Hope you understand it right now and thanks anyway.

**Pull request closed without merging**
