### PR TITLE
Added two XML layouts for ServerWMC integration

### PR DESCRIPTION
**Pull request by mainLink0435**

### CODE REVIEW

**Comment by vonH** [comment]
Can you provide a little more information (I've read the Kodi Wiki) as well as a couple of screen shots? From a quick look it should be fine, but I don't use that pvr add-on so can't test/check.

**Comment by mainlink0435** [comment]
recordprefs
deletetimer
These xml files help ServerWMC record series (and delete series) rather than 1-off TV show recordings. Syncs with WMC recording schedule.

**Comment by vonH** [comment]
Can you add a fade to the dialogue? Then we're good to go.

**Comment by mainlink0435** [comment]
unfortunately I have no idea how to do that.. I just copied these two xml files from another skin and they just worked.. do you know how to add the fade?

**Comment by vonH** [comment]
Yep, I make sure they are properly integrated. I need some sort of way to test this new dialog, I don't use the same PVR backend.

**Comment by mainlink0435** [comment]
OK happy to help out, just tell me what testing you'd like me to do.

**Comment by vonH** [comment]
@benpage please can you test this out with the current version of the skin (the Isengard one). Let me know how it works and if anything needs to be added. Actually a video would be ideal, if you have time. If not then four or five screenshots of each step would be acceptable.

I can then make changes required so it's included in the final version.

**Pull request merged**
